import { PricingBlock } from "@/components/constructor/page-render/types";

export const pricingCardsEn: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Starter Pack",
        price: "10",
        tokens: 1000,
        description: "For individuals who need a few QR codes.",
        features: [
            "Up to 10 QR codes",
            "Basic customization",
            "Download in PNG/JPG",
            "No expiration",
        ],
        buttonText: "Buy Now",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro Pack",
        price: "20",
        tokens: 2000,
        description: "For professionals and small teams.",
        features: [
            "Up to 50 QR codes",
            "Advanced customization (colors, logos)",
            "High-resolution exports",
            "Best value for growing teams",
        ],
        buttonText: "Get Pro",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business Pack",
        price: "40",
        tokens: 4000,
        description: "For businesses with ongoing QR needs.",
        features: [
            "Unlimited QR codes",
            "Full customization",
            "Priority support",
            "Bulk download/export",
        ],
        buttonText: "Go Business",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Custom Pack",
        price: "dynamic",
        tokens: 0,
        description: "Define your own package and get instant pricing.",
        features: [
            "Flexible number of QR codes",
            "Custom features",
            "No expiration",
            "Perfect for enterprises",
        ],
        buttonText: "Buy Custom",
        buttonLink: "/pricing",
    },
];

export const pricingCardsEl: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Πακέτο Εκκίνησης",
        price: "10",
        tokens: 1000,
        description: "Για άτομα που χρειάζονται λίγους κωδικούς QR.",
        features: [
            "Έως 10 κωδικοί QR",
            "Βασική προσαρμογή",
            "Λήψη σε PNG/JPG",
            "Χωρίς λήξη",
        ],
        buttonText: "Αγορά",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Πακέτο Pro",
        price: "20",
        tokens: 2000,
        description: "Για επαγγελματίες και μικρές ομάδες.",
        features: [
            "Έως 50 κωδικοί QR",
            "Προηγμένη προσαρμογή (χρώματα, λογότυπα)",
            "Εξαγωγές υψηλής ανάλυσης",
            "Η καλύτερη αξία για αναπτυσσόμενες ομάδες",
        ],
        buttonText: "Αποκτήστε Pro",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Πακέτο Business",
        price: "40",
        tokens: 4000,
        description: "Για επιχειρήσεις με συνεχείς ανάγκες QR.",
        features: [
            "Απεριόριστοι κωδικοί QR",
            "Πλήρης προσαρμογή",
            "Προτεραιότητα υποστήριξης",
            "Μαζική λήψη/εξαγωγή",
        ],
        buttonText: "Επιλέξτε Business",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Προσαρμοσμένο Πακέτο",
        price: "dynamic",
        tokens: 0,
        description: "Ορίστε το δικό σας πακέτο και λάβετε άμεση τιμολόγηση.",
        features: [
            "Ευέλικτος αριθμός κωδικών QR",
            "Προσαρμοσμένα χαρακτηριστικά",
            "Χωρίς λήξη",
            "Ιδανικό για επιχειρήσεις",
        ],
        buttonText: "Αγορά Προσαρμοσμένου",
        buttonLink: "/pricing",
    },
];

export const pricingCardsDa: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Startpakke",
        price: "10",
        tokens: 1000,
        description: "Til personer, der har brug for et par QR-koder.",
        features: [
            "Op til 10 QR-koder",
            "Grundlæggende tilpasning",
            "Download i PNG/JPG",
            "Ingen udløb",
        ],
        buttonText: "Køb nu",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro-pakke",
        price: "20",
        tokens: 2000,
        description: "Til professionelle og små teams.",
        features: [
            "Op til 50 QR-koder",
            "Avanceret tilpasning (farver, logoer)",
            "Eksport i høj opløsning",
            "Bedste værdi for voksende teams",
        ],
        buttonText: "Få Pro",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business-pakke",
        price: "40",
        tokens: 4000,
        description: "Til virksomheder med løbende QR-behov.",
        features: [
            "Ubegrænsede QR-koder",
            "Fuld tilpasning",
            "Prioriteret support",
            "Massedownload/eksport",
        ],
        buttonText: "Vælg Business",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Tilpasset Pakke",
        price: "dynamic",
        tokens: 0,
        description: "Definer din egen pakke og få øjeblikkelig prissætning.",
        features: [
            "Fleksibelt antal QR-koder",
            "Tilpassede funktioner",
            "Ingen udløb",
            "Perfekt til virksomheder",
        ],
        buttonText: "Køb Tilpasset",
        buttonLink: "/pricing",
    },
];

export const pricingCardsHu: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Kezdő Csomag",
        price: "10",
        tokens: 1000,
        description: "Azoknak, akiknek néhány QR-kódra van szükségük.",
        features: [
            "Legfeljebb 10 QR-kód",
            "Alapvető testreszabás",
            "Letöltés PNG/JPG formátumban",
            "Nincs lejárat",
        ],
        buttonText: "Vásárlás",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro Csomag",
        price: "20",
        tokens: 2000,
        description: "Szakembereknek és kis csapatoknak.",
        features: [
            "Legfeljebb 50 QR-kód",
            "Haladó testreszabás (színek, logók)",
            "Nagy felbontású exportálás",
            "Legjobb érték növekvő csapatoknak",
        ],
        buttonText: "Pro Választás",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business Csomag",
        price: "40",
        tokens: 4000,
        description: "Folyamatos QR-igényekkel rendelkező vállalkozásoknak.",
        features: [
            "Korlátlan QR-kód",
            "Teljes testreszabás",
            "Elsőbbségi támogatás",
            "Tömeges letöltés/exportálás",
        ],
        buttonText: "Business Választás",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Egyedi Csomag",
        price: "dynamic",
        tokens: 0,
        description: "Határozza meg saját csomagját és kapjon azonnali árajánlatot.",
        features: [
            "Rugalmas QR-kód mennyiség",
            "Egyedi funkciók",
            "Nincs lejárat",
            "Tökéletes vállalatok számára",
        ],
        buttonText: "Egyedi Vásárlás",
        buttonLink: "/pricing",
    },
];

export const pricingCardsTr: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Baslangic Paketi",
        price: "10",
        tokens: 1000,
        description: "Az sayida QR koda ihtiyac duyan bireyler icin.",
        features: [
            "10 adede kadar QR kod",
            "Temel ozellestirme",
            "PNG/JPG indirme",
            "Suresiz kullanim",
        ],
        buttonText: "Satın Al",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro Paketi",
        price: "20",
        tokens: 2000,
        description: "Profesyoneller ve kucuk ekipler icin.",
        features: [
            "50 adede kadar QR kod",
            "Gelismis ozellestirme (renkler, logolar)",
            "Yuksek cozunurlukte export",
            "Buyuyen ekipler icin en iyi deger",
        ],
        buttonText: "Pro Ol",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business Paketi",
        price: "40",
        tokens: 4000,
        description: "Surekli QR ihtiyaci olan isletmeler icin.",
        features: [
            "Sinirsiz QR kod",
            "Tam ozellestirme",
            "Oncelikli destek",
            "Toplu indirme/export",
        ],
        buttonText: "Business'a Gec",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Ozel Paket",
        price: "dynamic",
        tokens: 0,
        description: "Kendi paketinizi belirleyin ve aninda fiyat alin.",
        features: [
            "Esnek QR miktari",
            "Ozel ozellikler",
            "Suresiz kullanim",
            "Kurumsal ihtiyaclar icin uygun",
        ],
        buttonText: "Ozel Satin Al",
        buttonLink: "/pricing",
    },
];
