import { PricingBlock } from "@/components/constructor/page-render/types";

export const pricingCardsEn: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Starter Pack",
        price: "10",
        tokens: 1000,
        description: "For individuals who need a few QR codes.",
        features: [
            "Up to 10 QR codes",
            "Basic customization",
            "Download in PNG/JPG",
            "No expiration",
        ],
        buttonText: "Buy Now",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro Pack",
        price: "20",
        tokens: 2000,
        description: "For professionals and small teams.",
        features: [
            "Up to 50 QR codes",
            "Advanced customization (colors, logos)",
            "High-resolution exports",
            "Best value for growing teams",
        ],
        buttonText: "Get Pro",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business Pack",
        price: "40",
        tokens: 4000,
        description: "For businesses with ongoing QR needs.",
        features: [
            "Unlimited QR codes",
            "Full customization",
            "Priority support",
            "Bulk download/export",
        ],
        buttonText: "Go Business",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Custom Pack",
        price: "dynamic",
        tokens: 0,
        description: "Define your own package and get instant pricing.",
        features: [
            "Flexible number of QR codes",
            "Custom features",
            "No expiration",
            "Perfect for enterprises",
        ],
        buttonText: "Buy Custom",
        buttonLink: "/pricing",
    },
];

export const pricingCardsTr: PricingBlock[] = [
    {
        type: "pricing",
        variant: "basic",
        title: "Baslangic Paketi",
        price: "10",
        tokens: 1000,
        description: "Az sayida QR koda ihtiyac duyan bireyler icin.",
        features: [
            "10 adede kadar QR kod",
            "Temel ozellestirme",
            "PNG/JPG indirme",
            "Suresiz kullanim",
        ],
        buttonText: "Satın Al",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "highlight",
        title: "Pro Paketi",
        price: "20",
        tokens: 2000,
        description: "Profesyoneller ve kucuk ekipler icin.",
        features: [
            "50 adede kadar QR kod",
            "Gelismis ozellestirme (renkler, logolar)",
            "Yuksek cozunurlukte export",
            "Buyuyen ekipler icin en iyi deger",
        ],
        buttonText: "Pro Ol",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "premium",
        title: "Business Paketi",
        price: "40",
        tokens: 4000,
        description: "Surekli QR ihtiyaci olan isletmeler icin.",
        features: [
            "Sinirsiz QR kod",
            "Tam ozellestirme",
            "Oncelikli destek",
            "Toplu indirme/export",
        ],
        buttonText: "Business'a Gec",
        buttonLink: "/pricing",
    },
    {
        type: "pricing",
        variant: "basic",
        title: "Ozel Paket",
        price: "dynamic",
        tokens: 0,
        description: "Kendi paketinizi belirleyin ve aninda fiyat alin.",
        features: [
            "Esnek QR miktari",
            "Ozel ozellikler",
            "Suresiz kullanim",
            "Kurumsal ihtiyaclar icin uygun",
        ],
        buttonText: "Ozel Satin Al",
        buttonLink: "/pricing",
    },
];
